# Production overrides — Kubernetes environment
spring.datasource.url=jdbc:postgresql://postgres:5432/ictuex
spring.datasource.username=ictuex_user
spring.datasource.password=ictuex_pass
server.port=8080

# Kafka — k3s internal DNS
spring.kafka.bootstrap-servers=kafka.ictu-ex.svc.cluster.local:9092
spring.kafka.admin.properties.bootstrap.servers=kafka.ictu-ex.svc.cluster.local:9092