spring.application.name=ictu-ex-backend
server.port=8080

# Database - local docker
spring.datasource.url=jdbc:postgresql://localhost:5433/ictuex
spring.datasource.username=ictuex_user
spring.datasource.password=ictuex_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG

# Kafka — default for local dev
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.client-id=ictu-ex-backend-producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.jpa.open-in-view=false

# Actuator for Prometheus
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

# JWT Settings (Used by the Auth module)
jwt.secret=${JWT_SECRET:default-secret-for-local-dev}
jwt.expiration=${JWT_EXPIRES:86400000}

# resend api key(Used by notification module)
resend.api.key=${RESEND_API_KEY:dummy-key-for-local}

# Jackson Settings
spring.jackson.deserialization.fail-on-unknown-properties=false

# Redis — local dev
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method

# Enable the specific liveness and readiness endpoints
management.endpoint.health.probes.enabled=true
# Optional: Ensure Kafka/DB issues show up in health checks
management.health.kafka.enabled=true
management.health.db.enabled=true


