name: SonarCloud Code Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize JDK 21 Environment
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Execute Permissions
        run: chmod +x gradlew

      - name: Execute Background Code Coverage & Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew clean test koverXmlReport sonar -Dsonar.token=$SONAR_TOKEN --dependency-verification=off
